# Generated by Django 3.1.2 on 2020-11-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dateTimeCreated',
            new_name='date_time_created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionType',
            new_name='question_type',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='givenAnswer',
            new_name='given_answer',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='dateTimeCreated',
            new_name='date_time_created',
        ),
        migrations.RenameField(
            model_name='testresults',
            old_name='dateTimeCreated',
            new_name='date_time_created',
        ),
    ]
