# Generated by Django 3.1.2 on 2020-11-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_auto_20201125_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
