# Generated by Django 3.1.2 on 2020-12-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0004_course_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isHidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
