# Generated by Django 3.1.2 on 2020-12-01 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webproject', '0005_auto_20201201_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='testResults',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject.testanswers'),
        ),
        migrations.DeleteModel(
            name='TestResults',
        ),
    ]
