# Generated by Django 3.1.2 on 2020-12-15 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webproject', '0007_auto_20201201_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='cost',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='questionanswer',
            old_name='points',
            new_name='total_points',
        ),
        migrations.RemoveField(
            model_name='course',
            name='isHidden',
        ),
        migrations.RemoveField(
            model_name='questionanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='correct_answer',
            field=models.CharField(default='Pepega', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question_text',
            field=models.CharField(default='Pepega', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='scored_points',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject.test')),
            ],
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='testResults',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webproject.testresult'),
        ),
        migrations.DeleteModel(
            name='TestResults',
        ),
    ]
