# Generated by Django 3.1.2 on 2020-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0008_auto_20201215_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['date_time_created']},
        ),
    ]
