# Generated by Django 3.1.2 on 2020-12-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0009_auto_20201216_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
