# Generated by Django 3.1.2 on 2020-12-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0010_auto_20201216_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
