# Generated by Django 3.1.2 on 2020-12-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0011_auto_20201216_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
    ]
