# Generated by Django 3.1.2 on 2020-12-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0012_auto_20201216_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='testResults',
            new_name='testResult',
        ),
    ]
