# Generated by Django 3.1.4 on 2020-12-29 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0013_auto_20201217_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-date_time_created']},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=50, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='балл за правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='correct_answer',
            field=models.CharField(max_length=50, verbose_name='верный ответ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='given_answer',
            field=models.CharField(max_length=50, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='scored_points',
            field=models.IntegerField(default=0, verbose_name='полученный балл'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='total_points',
            field=models.IntegerField(verbose_name='балл за правильный ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название теста'),
        ),
    ]
